### ISSUE TITLE
Add support for wget

### ISSUE THREAD

**Issue by jamieson99** [userify/shim#27]
It'd be relatively simple to add a check for wget instead of curl, since Debian and FreeBSD in minimal installs don't have curl.

**Comment by ansarid** [comment]
`wget` would be a nice improvement. I wrote a quick script to determine whether to use `wget` or `curl`.
```
# Check for curl or wget
if command -v curl  >>/dev/null 2>&1; then
    # echo "${GREEN_TEXT}Found curl.${RESET_TEXT}" >&2
    export GET_METHOD="curl"
else
    if command -v wget  >>/dev/null 2>&1; then
        # echo "${GREEN_TEXT}Found wget.${RESET_TEXT}" >&2
        export GET_METHOD="wget"
    else 
        echo "${RED_TEXT}Could not find curl or wget!.${RESET_TEXT}" >&2
        exit 1
    fi
fi
```
I have it save the get method as an environment variable that can be called later at the curl/wget shim.py line.
```
${GET_METHOD} --compressed -1 -f${SELFSIGNED}Ss https://$static_host/shim.py | $PYTHON -u \
    2>&1 >> /var/log/userify-shim.log
```
Now the options between wget and curl are a bit different so I think that's the last thing I need to do to have this script support both curl and wget.

**Comment by jamiesonbecker** [comment]
@ansarid Excellent! I'll put some more thought into how this could be integrated. Unfortunately, currently we use curl in at least three different places.

Normally I use wget -O- to direct to stdout (as curl does by default, while wget defaults to saving it as a file), so we'd have to check above not only which is available, but also change the actual options (as you point out).

It might be best to actually perform the command itself with custom switches inside those `if` blocks rather than export GET_METHOD.

What system are you using this on that doesn't have curl? (minimal Debian?) We could always add it to the apt-get, since we already do that for Python if not installed, but it would be much faster to not have to install curl at all and just do it this way.

**Comment by ansarid** [comment]
@jamiesonbecker 

> But it might be best to actually perform the command itself with custom switches inside those if blocks rather than export GET_METHOD.

That makes more sense. I'd do that instead now that you mentioned it.

**Comment by userifydevteam** [comment]
This is probably no longer relevant, but please re-open if so.
