### ISSUE TITLE
Separate Logrotate?

### ISSUE THREAD

**Issue by jpartain89** [userify/shim#37]
Should there be a separate means of handling the logrotate functions? As in, offloading that logging management from the `shim` to the system-built logrotate. This way, if we want a longer log, or a corporation has a different type of requirement, they can have and manage that separately.

**Comment by cthurbson** [comment]
This could be a good thing but then it wouldn't rotate at the end or beginning of a poll cycle. Also logrotate isn't always available (and would require another distribution file in etc). It'd be nice if it was detected and autoconfigured, but it'd have to be triggered by userify, not by cron.

**Comment by jamiesonbecker** [comment]
Yeah, @jpartain89 you raise some good points.  I think we want to keep that built into the shim.sh for now since it works pretty well with a balance of time but we should definitely allow extra growth of that.. perhaps a config option. Let's keep this bug open. Is this an institutional requirement for your team?

**Comment by jamiesonbecker** [comment]
We're going to continue to self-manage logs, but we'll probably also continue to log to syslog so that you can manage your own logs if you wish. Closing this issue for now.
