### ISSUE TITLE
Starts up twice on Amazon Linux 2016

### ISSUE THREAD

**Issue by cthurbson** [userify/shim#39]
The shim starts up twice on Amazon Linux 2016, but only on the first boot (might be only for CloudFormation).

This is completely harmless except for a few error messages in the log, (any errors are immediately resolved, and no concurrency issues), but tracking this as a bug.

**Comment by jamiesonbecker** [comment]
See also https://github.com/userify/shim/issues/23. This seems to be related to startup script detection. It should be resolved when we move most distros over to full systemd support (though not Amazon, since it's not a systemd distro). Let's keep an eye on this. I could see it becoming an issue down the road when we go websockets.

**Comment by cthurbson** [comment]
The second startup only occurs on initial install.

**Comment by jamiesonbecker** [comment]
This only seems to occur on Amazon Linux version 1, which is going away (this doesn't happen on Amazon Linux 2), and it doesn't cause any problems anyway (the instances don't conflict). Closing this issue.
