### ISSUE TITLE
Add troubleshooting section to the README

### ISSUE THREAD

**Issue by pnomolos** [userify/shim#42]
I just spent an hour banging my head against my monitor because I had two calls to `curl -1 -sS "https://static.userify.com/installer.sh"` in my `cloud-init` file.  Unfortunately, due to the way cloud-init works, of course that just meant that I couldn't ssh into my server to figure out what was causing things to fail.

Would it be too much ask to add a simple troubleshooting section in the README for poor souls like me? ;)

**Comment by jamiesonbecker** [comment]
Pull requests gratefully accepted. ;)

This is an interesting one. That should have still worked. Even multiple instances of the installer or shim running should work (although maybe not at the exact same instant). If the installer sees another installed edition, it should abort. That might have caused your whole cloudformation template to fail, though.

Although I recommend not using the standard AWS keypair service in general, for troubleshooting it can be pretty handy in this sort of automated deployment model as well, since you need some way to spot if you have a typo or something like that.

Funny that you mention it... we reject some servers because they're trying to log in with the API key "change_me". Not just a few, but a _lot_. That will probably never work. ;)

**Comment by pnomolos** [comment]
@jamiesonbecker Yeah, I believe that the issue was the template failing and that cascading.  Alternatively, may have been this next problem ... I know this shouldn't be used for troubleshooting, but while we're adding a section to the README, I'm also seeing the following problem:

```
/opt/userify/shim.sh: line 26: -u: command not found
curl: (23) Failed writing body (0 != 16011)
```

If I'm reading the script correctly, it's because `python` isn't installed.  In my case I think there's some sort of race condition with python being installed, as I have `python` in my `packages:` section of the cloud-init file, but adding a note may be helpful in at least pointing people in the right direction.

And finally, another question - does userify sync users immediately after install, or will it be sometime within a 90s period that the users are synced?  I'm trying to streamline my provisioning scripts and have been adding a manual `sleep 90` call, but would like to remove that if I can :)

**Comment by jamiesonbecker** [comment]
1) interesting, and your take seems to be a pretty accurate guess to me. Is this ubuntu 16.04/16.10 on EC2 by any chance? That packages: python is precisely for this problem, so you're probably right... we may need to wait an indefinite period if it's parallelizing the scripts. That's a bit frustrating... indefinite waits add a lot of complexity.

2) users get synced upon the first request, which occurs instantly, as soon as the shim installs. go ahead and remove the `sleep 90`. ;)

Also, wrt #2, you can go down to a 5 or 10 second wait with AWS Express or Datacenter Express. (highly recommended, since they're also much more secure and cheaper per server, especially datacenter.)

**Comment by pnomolos** [comment]
@jamiesonbecker Yep, 16.04 on EC2.  There's definitely something going on with cloud-init there, as in looking at the cloud-init log files the packages I'm listing to be installed aren't being due to a locking issue.  For now I can build those in directly with packer, but yes, frustrating to say the least.  Waiting (indefinitely) for the lock to become available might do the trick, but that does add a whole new layer of potential problems.

**Comment by jamiesonbecker** [comment]
@pnomolos here's a 15% discount coupon for Datacenter Express: KNOCKOFF15

**Comment by pnomolos** [comment]
@jamiesonbecker Thanks!  I'll try and put a PR together with a troubleshooting section for the readme today :)

**Comment by jamiesonbecker** [comment]
Awesome thanks a ton!! I'll add to it too.
