### ISSUE TITLE
Authorized keys can't be found due to non-standard /home folders

### ISSUE THREAD

**Issue by albrandwood** [userify/shim#46]
Unable to add SSH key for user it-ab: [Errno 2] No such file or directory: u'/home/it-ab/.ssh/authorized_keys'

Not surprising, since that isn't the path to the user's home folder ... When it's a "userify-converted" user, you should check the home folder listed in /etc/passwd:

In this instance:

it-ab:x:501:501:userify-converted:/home/ashley:/bin/bash

Seems like a simple check ... "let me see what the user's home folder is, before I assume it to be /home/user" ... 

This would also be an issue for a lot of AD bound systems, as they tend to use the home path format of "/home/DOMAIN/userid"

@shley

**Comment by jamiesonbecker** [comment]
To be clear, you're suggesting that since we're parsing /etc/passwd anyway, we should use that home directory as the given homedir? Seems like a good idea.

What about when the user acct is removed and then restored? We'd need to store state somewhere that deleted home directories were stored in a particular place other than just /home. (We try to avoid tracking state on the client too much and make few assumptions, but we could also track uid/gid of prior user accounts in the same location.)

(not relevant to this problem, but as soon as we become uid/gid aware, then we have to worry about uid/gid reuse etc, instead of just letting the OS handle everything. a current design goal of userify is not to take over user's long-running directories, but to essentially provide a once-and-done ephemeral home directory in the simplest, cleanest way possible. maybe it's time to expand that vision in support of making userify useful for desktop mgmt as well, which could tie in nicely with our expansion to Windows server support later this year.)

Solving this might be a really nice enhancement especially as we expand to support various unix systems, osx, etc where home directories might be in a different location by default (i.e., /export/home, etc)

**Comment by userifydevteam** [comment]
We're revisiting some of these old enhancement requests in preparation for the new release.

This seems particularly challenging for deleted home directories, and the use case might be too narrow. If you can provide some additional details on how this could be useful if this would still be useful to you, please provide those and re-open the issue. Thanks very much!
