### ISSUE TITLE
Alpine Linux Support

### ISSUE THREAD

**Issue by idralyuk** [userify/shim#47]
Would like to use Userify with [Moby](https://github.com/moby/moby), which is based on Alpine Linux, that unfortunately has a non-standard useradd (adduser).

**Comment by jamiesonbecker** [comment]
Thanks Igor - this is an important one. We're working through the design for the next shim release now, so we'll keep this open. It looks like adduser implementations differ between distros, unfortunately, so we'll have to detect which we're on. (For example, the adduser -D switch in Alpine doesn't exist in Debian.) I wonder how much of this will be similar on FreeBSD (also uses adduser IIRC) and/or OSX (no idea).

**Comment by idralyuk** [comment]
Would still like to see an Alpine version of the shim, but in the meantime, I created [idralyuk/docker-userify](https://github.com/idralyuk/docker-userify).

It is a [lambda-linux](https://github.com/lambda-linux/baseimage-amzn)-based image that runs sshd and userify.

**Comment by jamiesonbecker** [comment]
@idralyuk That is great!!

And, yes, the Alpine version of the shim is moving forward! The challenge at this point is switchable TLS support, but it's under active development!!

This is really great and I am sure that there are some other users that will be interested in using this as well. We're moving forward on a bunch of different initiatives simultaneously, and I'm not sure which one will hit first. (BTW, Igor, please send an email to beta@userify.com to jump on early access!) 

Nice work!!

**Comment by cthurbson** [comment]
For example,

`adduser -D -g userify-cthurbson -s /bin/bash cthurbson`

This is the busybox binary but supports everything that userify needs (except python, but the new shim should remove that requirement and also solve #29, #28, and #24.

**Comment by jamiesonbecker** [comment]
We just updated the shim so that it's Python 2/3 compatible, but that is not the end game for us. We're currently developing a small, statically compiled shim that can be deployed with no dependencies even on musl libc systems like Alpine. This will by necessity be a larger binary, which means we have to improve the bandwidth efficiency of updates, so we have to have improved backend support for it as well. That's why this is taking so long, but we're hoping to have it finished within the next few months.

**Comment by userifydevteam** [comment]
Consolidating this into #53
