### ISSUE TITLE
shim.py does not work in FIPS environment.

### ISSUE THREAD

**Issue by JuddTracy** [userify/shim#57]
The shim does not work correctly when FIPS is enabled because the MD5 hash is disabled for cryptographic functions.

Switching to SHA265 should be fairly trivial.

**Comment by userifydevteam** [comment]
Judd, thanks for the excellent bug report! You're right, and we're just using it for file comparison testing, but since we don't have an excellent non-cryptographic hash function like xxhash or murmur in the stdlib, we should probably choose something from the SHA2 family, and it won't really impact performance on the instances if we're only doing a single one every few seconds.

We'll research this further, make a decision, and get back to you asap.

Which environment are in (Userify Cloud/SaaS, Express or Enterprise/self-hosted)?

**Comment by JuddTracy** [comment]
Thanks for looking at this.

I don't know how often the shim gets updated but on my systems it will not update because of this.  I hope it wont cause issues with old shims running.

We are Userify Cloud.
